version: 2

sources:
  - name: bronze
    meta:
      external_location: "../lake/bronze/{name}/*/*.parquet"
    tables:
      - name: customers
      - name: products
      - name: orders
      - name: order_items
      - name: inventory
      - name: clickstream_events
      - name: marketing_google
      - name: marketing_meta
      - name: marketing_email
      - name: payments
      - name: support_tickets
      - name: shipments
      - name: weather_daily
