version: 2

sources:
  - name: bronze
    meta:
      external_location: "../lake/bronze/{name}/*/*.parquet"
    tables:
      - name: customers
      - name: products
      - name: orders
      - name: order_items
      - name: inventory
