version: 2
sources:
  - name: bronze
    meta:
      external_location: "../lake/bronze/{name}/*/*.parquet"
    tables:
      - name: customers
      - name: products
      - name: orders
        loaded_at_field: updated_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 72, period: hour}
      - name: order_items
      - name: inventory
      - name: clickstream_events
      - name: marketing_google
      - name: marketing_meta
      - name: marketing_email
      - name: payments
      - name: support_tickets
      - name: shipments
      - name: weather_daily
      - name: product_reviews
      - name: knowledge_base_articles
